name: Managerapi
version: ${project.version}
main: me.bdx.managerapi.Managerapi
api-version: 1.17
softdepend: [Essentials, Vault]


commands:

  chatcommand:
    description: this is the global chat command
    aliases: [sc, dc, g]
    usage: /<command> <msg>

  managerapireload:
    description: This command reloads the config for the manager api plugin
    aliases: [mareload]
    usage: /<command>

  staff:
    description: shows all online staff
    aliases: [showstaff]

  playerinfo:
    description: Shows info of a given player
    aliases: [pinfo, userinfo, user]

  gchat:
    description: Options on enabling and disabling chat
    aliases: [globalchat]

  globalcommand:
    description: This command allows for one command to be executed by console on all servers.
    aliases:
      - gcommand
      - gcmd


permissions:
  managerapi.*:
    children:
      managerapi.chatcommand: true
      managerapi.reload: true
      managerapi.chat: true
      managerapi.chatcommand.devchat: true
      managerapi.chatcolor.dred: true
      managerapi.chatcolor.lred: true
      managerapi.chatcolor.blue: true
      managerapi.chatcolor.white: true
      managerapi.staff: true
      managerapi.autoop: true
      managerapi.stafflist: true
      managerapi.player.info: true
      managerapi.chat.bypass: true
      managerapi.globalcommand: true
      managerapi.globalcommand.notify: true
